"""Clean crawled JD FAQ JSONL data for retrieval / knowledge-base use.

Input:
    data/jd_faq.jsonl generated by scripts/crawl_jd_faq.py

Outputs:
    data/jd_faq_clean.jsonl      one cleaned record per FAQ
    data/jd_faq_clean.csv        CSV mirror for manual inspection
    data/jd_faq_chunks.jsonl     retrieval chunks with stable chunk ids
    data/jd_faq_clean_report.json

Examples:
    python3 scripts/clean_jd_faq.py
    python3 scripts/clean_jd_faq.py --input data/jd_faq.jsonl --chunk-size 900
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

DEFAULT_INPUT = Path("data/jd_faq.jsonl")
DEFAULT_OUTPUT = Path("data/jd_faq_clean.jsonl")
DEFAULT_CSV_OUTPUT = Path("data/jd_faq_clean.csv")
DEFAULT_CHUNKS_OUTPUT = Path("data/jd_faq_chunks.jsonl")
DEFAULT_REPORT_OUTPUT = Path("data/jd_faq_clean_report.json")

TAIL_DATE_RE = re.compile(r"(?:\n|\s)*(20\d{2}-\d{2}-\d{2})\s*$")
DATE_LINE_RE = re.compile(r"^20\d{2}-\d{2}-\d{2}$")
SPACE_RE = re.compile(r"[ \t\r\f\v]+")
MANY_BLANK_LINES_RE = re.compile(r"\n{3,}")
MOJIBAKE_RE = re.compile(r"[\ufffd]|(?:鐗|�)")

BOILERPLATE_LINES = {
    "这条帮助是否解决了您的问题？",
    "猜你感兴趣的问题",
    "很抱歉，我们暂时无相关信息，请您重新搜索。",
}


@dataclass
class CleanFAQRecord:
    id: str
    source: str
    category: str
    category_id: int
    question: str
    answer: str
    text: str
    url: str
    fetched_at: str
    published_at: str | None
    answer_chars: int
    quality: str
    quality_flags: list[str]
    kb_candidate: bool
    exclude_reasons: list[str]


@dataclass
class FAQChunk:
    id: str
    faq_id: str
    chunk_index: int
    chunk_count: int
    source: str
    category: str
    question: str
    text: str
    url: str


def normalize_question(value: str) -> str:
    value = normalize_text(value, keep_linebreaks=False)
    value = value.lstrip("·").strip()
    value = re.sub(r"\s*([？?])\s*$", r"\1", value)
    return value


def normalize_answer(value: str) -> tuple[str, str | None, list[str]]:
    flags: list[str] = []
    value = value or ""
    value = value.replace("\u3000", " ").replace("\xa0", " ")
    value = value.replace("点击查看", "").replace("（点击查看）", "")

    published_at = None
    match = TAIL_DATE_RE.search(value)
    if match:
        published_at = match.group(1)
        value = value[: match.start()]
        flags.append("removed_tail_date")

    lines = []
    seen_blank = False
    for raw_line in value.splitlines():
        line = normalize_text(raw_line, keep_linebreaks=False)
        if not line:
            if not seen_blank:
                lines.append("")
            seen_blank = True
            continue
        seen_blank = False
        if line in BOILERPLATE_LINES:
            flags.append("removed_boilerplate")
            continue
        if DATE_LINE_RE.fullmatch(line):
            published_at = published_at or line
            flags.append("removed_date_line")
            continue
        lines.append(line)

    value = "\n".join(lines).strip()
    value = MANY_BLANK_LINES_RE.sub("\n\n", value)
    return value, published_at, flags


def normalize_text(value: str, *, keep_linebreaks: bool = True) -> str:
    value = value or ""
    value = value.replace("\u3000", " ").replace("\xa0", " ")
    if keep_linebreaks:
        value = "\n".join(SPACE_RE.sub(" ", line).strip() for line in value.splitlines())
        return MANY_BLANK_LINES_RE.sub("\n\n", value).strip()
    return SPACE_RE.sub(" ", value.replace("\n", " ")).strip()


def stable_id(url: str) -> str:
    return hashlib.sha1(url.encode("utf-8")).hexdigest()[:16]


def quality_for(question: str, answer: str) -> tuple[str, list[str]]:
    flags: list[str] = []
    if not question:
        flags.append("empty_question")
    if not answer:
        flags.append("empty_answer")
    if len(answer) < 30:
        flags.append("very_short_answer")
    elif len(answer) < 80:
        flags.append("short_answer")
    if len(answer) > 5000:
        flags.append("long_policy_text")
    if MOJIBAKE_RE.search(question) or MOJIBAKE_RE.search(answer):
        flags.append("possible_mojibake")

    if "empty_question" in flags or "empty_answer" in flags or "possible_mojibake" in flags:
        return "bad", flags
    if "very_short_answer" in flags:
        return "review", flags
    return "ok", flags


def kb_suitability(question: str, answer: str, quality: str) -> tuple[bool, list[str]]:
    """Decide whether a record should enter retrieval chunks by default.

    A page can be well-formed but still unsuitable for a customer-service KB:
    historical announcements, voting solicitations, expired policy snapshots,
    legal agreements, and image-dependent answers often hurt retrieval quality.
    The cleaned FAQ file keeps them for traceability; chunks exclude them by default.
    """
    reasons: list[str] = []
    combined = f"{question}\n{answer}"

    if quality == "bad":
        reasons.append("bad_quality")
    if re.search(r"公开意见征集|意见征集|征集|投票|扫描下方二维码|点击去投票", combined):
        reasons.append("announcement_or_solicitation")
    if re.search(r"已失效|失效", question):
        reasons.append("expired_policy")
    if re.search(r"隐私政策|用户服务协议|服务协议|线上用户服务协议", question):
        reasons.append("legal_or_agreement_text")
    if re.search(r"20\d{2}年\d{1,2}月\d{1,2}日\s*[-至]", question):
        reasons.append("historical_policy_snapshot")
    if "[图片：" in answer and len(answer) < 220:
        reasons.append("image_dependent_answer")

    return not reasons, reasons


def clean_record(raw: dict[str, Any]) -> CleanFAQRecord:
    question = normalize_question(str(raw.get("question", "")))
    answer, published_at, flags = normalize_answer(str(raw.get("answer", "")))
    quality, quality_flags = quality_for(question, answer)
    quality_flags = [*flags, *quality_flags]
    kb_candidate, exclude_reasons = kb_suitability(question, answer, quality)
    url = str(raw.get("url", ""))
    faq_id = stable_id(url or f"{raw.get('category')}:{question}")
    text = f"问题：{question}\n答案：{answer}"

    return CleanFAQRecord(
        id=faq_id,
        source=str(raw.get("source", "京东帮助中心")),
        category=str(raw.get("category", "")),
        category_id=int(raw.get("category_id", 0) or 0),
        question=question,
        answer=answer,
        text=text,
        url=url,
        fetched_at=str(raw.get("fetched_at", "")),
        published_at=published_at,
        answer_chars=len(answer),
        quality=quality,
        quality_flags=quality_flags,
        kb_candidate=kb_candidate,
        exclude_reasons=exclude_reasons,
    )


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    rows = []
    with path.open("r", encoding="utf-8") as fp:
        for line_no, line in enumerate(fp, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as exc:
                raise ValueError(f"Invalid JSONL at {path}:{line_no}: {exc}") from exc
    return rows


def dedupe(records: list[CleanFAQRecord]) -> tuple[list[CleanFAQRecord], dict[str, int]]:
    seen_urls: set[str] = set()
    seen_qa: set[tuple[str, str]] = set()
    output: list[CleanFAQRecord] = []
    stats = {"duplicate_url": 0, "duplicate_question_answer": 0}

    for record in records:
        if record.url and record.url in seen_urls:
            stats["duplicate_url"] += 1
            continue
        qa_key = (record.question, record.answer)
        if qa_key in seen_qa:
            stats["duplicate_question_answer"] += 1
            continue
        seen_urls.add(record.url)
        seen_qa.add(qa_key)
        output.append(record)
    return output, stats


def split_answer(answer: str, *, chunk_size: int, overlap: int) -> list[str]:
    answer = answer.strip()
    if len(answer) <= chunk_size:
        return [answer] if answer else []

    parts = [p.strip() for p in re.split(r"\n{2,}", answer) if p.strip()]
    chunks: list[str] = []
    current = ""

    for part in parts:
        if len(part) > chunk_size:
            if current:
                chunks.append(current.strip())
                current = ""
            chunks.extend(split_long_text(part, chunk_size=chunk_size, overlap=overlap))
            continue
        candidate = f"{current}\n\n{part}".strip() if current else part
        if len(candidate) <= chunk_size:
            current = candidate
        else:
            chunks.append(current.strip())
            current = part
    if current:
        chunks.append(current.strip())
    return chunks


def split_long_text(text: str, *, chunk_size: int, overlap: int) -> list[str]:
    chunks = []
    start = 0
    while start < len(text):
        end = min(len(text), start + chunk_size)
        if end < len(text):
            punctuation_cut = max(text.rfind(mark, start, end) for mark in "。！？；\n")
            if punctuation_cut > start + chunk_size * 0.5:
                end = punctuation_cut + 1
        chunks.append(text[start:end].strip())
        if end >= len(text):
            break
        start = max(end - overlap, start + 1)
    return [chunk for chunk in chunks if chunk]


def build_chunks(
    records: list[CleanFAQRecord],
    *,
    chunk_size: int,
    overlap: int,
    include_non_kb: bool = False,
) -> list[FAQChunk]:
    chunks: list[FAQChunk] = []
    for record in records:
        if not include_non_kb and not record.kb_candidate:
            continue
        answer_chunks = split_answer(record.answer, chunk_size=chunk_size, overlap=overlap)
        for index, answer_part in enumerate(answer_chunks):
            text = f"分类：{record.category}\n问题：{record.question}\n答案：{answer_part}"
            chunks.append(
                FAQChunk(
                    id=f"{record.id}-{index:03d}",
                    faq_id=record.id,
                    chunk_index=index,
                    chunk_count=len(answer_chunks),
                    source=record.source,
                    category=record.category,
                    question=record.question,
                    text=text,
                    url=record.url,
                )
            )
    return chunks


def write_jsonl(path: Path, rows: list[Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fp:
        for row in rows:
            payload = asdict(row) if hasattr(row, "__dataclass_fields__") else row
            fp.write(json.dumps(payload, ensure_ascii=False) + "\n")


def write_csv(path: Path, records: list[CleanFAQRecord]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(asdict(records[0]).keys()) if records else list(CleanFAQRecord.__dataclass_fields__)
    with path.open("w", encoding="utf-8-sig", newline="") as fp:
        writer = csv.DictWriter(fp, fieldnames=fieldnames)
        writer.writeheader()
        for record in records:
            row = asdict(record)
            row["quality_flags"] = "|".join(row["quality_flags"])
            writer.writerow(row)


def make_report(raw_count: int, records: list[CleanFAQRecord], chunks: list[FAQChunk], dedupe_stats: dict[str, int]) -> dict[str, Any]:
    by_category: dict[str, int] = {}
    kb_by_category: dict[str, int] = {}
    by_quality: dict[str, int] = {}
    flag_counts: dict[str, int] = {}
    exclude_reason_counts: dict[str, int] = {}
    for record in records:
        by_category[record.category] = by_category.get(record.category, 0) + 1
        if record.kb_candidate:
            kb_by_category[record.category] = kb_by_category.get(record.category, 0) + 1
        by_quality[record.quality] = by_quality.get(record.quality, 0) + 1
        for flag in record.quality_flags:
            flag_counts[flag] = flag_counts.get(flag, 0) + 1
        for reason in record.exclude_reasons:
            exclude_reason_counts[reason] = exclude_reason_counts.get(reason, 0) + 1

    lengths = sorted(record.answer_chars for record in records)
    length_report = {
        "min": lengths[0] if lengths else 0,
        "p50": lengths[len(lengths) // 2] if lengths else 0,
        "p90": lengths[int(len(lengths) * 0.9)] if lengths else 0,
        "max": lengths[-1] if lengths else 0,
    }
    return {
        "raw_records": raw_count,
        "clean_records": len(records),
        "kb_candidate_records": sum(1 for record in records if record.kb_candidate),
        "non_kb_records": sum(1 for record in records if not record.kb_candidate),
        "chunks": len(chunks),
        "by_category": by_category,
        "kb_by_category": kb_by_category,
        "by_quality": by_quality,
        "quality_flags": flag_counts,
        "exclude_reasons": exclude_reason_counts,
        "answer_chars": length_report,
        "dedupe": dedupe_stats,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Clean JD FAQ crawl output.")
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--csv-output", type=Path, default=DEFAULT_CSV_OUTPUT)
    parser.add_argument("--chunks-output", type=Path, default=DEFAULT_CHUNKS_OUTPUT)
    parser.add_argument("--report-output", type=Path, default=DEFAULT_REPORT_OUTPUT)
    parser.add_argument("--chunk-size", type=int, default=900)
    parser.add_argument("--chunk-overlap", type=int, default=120)
    parser.add_argument("--keep-bad", action="store_true", help="Keep records with empty answers or mojibake flags.")
    parser.add_argument("--include-non-kb", action="store_true", help="Include records marked unsuitable in retrieval chunks.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    raw_rows = load_jsonl(args.input)
    cleaned = [clean_record(row) for row in raw_rows]
    cleaned, dedupe_stats = dedupe(cleaned)
    dropped_bad = 0
    if not args.keep_bad:
        kept = [record for record in cleaned if record.quality != "bad"]
        dropped_bad = len(cleaned) - len(kept)
        cleaned = kept
    chunks = build_chunks(
        cleaned,
        chunk_size=args.chunk_size,
        overlap=args.chunk_overlap,
        include_non_kb=args.include_non_kb,
    )
    report = make_report(len(raw_rows), cleaned, chunks, dedupe_stats)
    report["dropped_bad_records"] = dropped_bad

    write_jsonl(args.output, cleaned)
    write_csv(args.csv_output, cleaned)
    write_jsonl(args.chunks_output, chunks)
    args.report_output.parent.mkdir(parents=True, exist_ok=True)
    args.report_output.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
